# Generated by Django 3.0.3 on 2020-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_game',
            name='purchased_date',
            field=models.DateField(auto_now=True),
        ),
    ]
