# Generated by Django 3.0.3 on 2020-03-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('type_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Game',
            fields=[
                ('user_game_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('purchased_date', models.DateTimeField()),
                ('serial', models.CharField(max_length=255)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonregister.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonregister.Regis')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('img_url', models.ImageField(upload_to='')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonregister.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonregister.Game_type'),
        ),
    ]
